### ISSUE TITLE
关于sdk取消订阅某一交易对的问题

### ISSUE THREAD

**Issue by BingDaXian** [huobiapi/huobi_Java#11]
如题，是不是sdk不提供取消订阅单个交易对的接口，在sdk中只找到了
![image](https://user-images.githubusercontent.com/49145629/57525551-a17d3180-735d-11e9-9ed0-664b50cfa6fd.png)取消区别的方法，如果我只取消订阅一个交易对，那我需要取消全部，然后再重新订阅吗。

**Comment by macomfan** [comment]
您好，是的，暂时不支持只取消一个交易对

**Comment by BingDaXian** [comment]
> 您好，是的，暂时不支持只取消一个交易对

您好，我看到websocket的api中是有这种描述的。sdk后期会考虑加进去这个接口吗。
