### ISSUE TITLE
订阅K线行情，无法获取历史数据

### ISSUE THREAD

**Issue by DanRui** [huobiapi/huobi_Java#14]
如题，传递了from和to参数，依旧得不到历史记录。还是实时的K线数据。
![image](https://user-images.githubusercontent.com/13469589/58691528-cd209400-83be-11e9-8cfe-6b0fa7fb298a.png)

**Comment by DanRui** [comment]
from和to范围是多少，怎么传都是错误的。
![image](https://user-images.githubusercontent.com/13469589/58698588-1af0c880-83ce-11e9-88e0-8743f41e553d.png)

**Comment by macomfan** [comment]
您好，通过WebSocket方式订阅K线，不支持from, to参数，有效参数只有symbol和interval
![Untitled](https://user-images.githubusercontent.com/11956667/58701743-58f1ea80-83d6-11e9-83e3-e7c2163c1c99.jpg)

**Comment by DanRui** [comment]
你好，我想获取历史K线数据，这个订阅是最新实时的K线不是我想要的。

**Comment by macomfan** [comment]
不好意思，刚才看了下，新的文档里已经写了订阅方式支持历史数据，请参考https://huobiapi.github.io/docs/spot/v1/cn/#k-2，如果有问题的话，可能是服务器接口出现问题

**Comment by DanRui** [comment]
您好，使用请求方式获取历史数据不支持自定义时间段吗，怎么传参都是不合法的。

**Comment by eynzhang** [comment]
@DanRui K线返回数据最多支持300条，您的时间段可能过大，需要调整一下时间段。
