### ISSUE TITLE
sdk中缺少文档中定义的`借贷账户详情`接口

### ISSUE THREAD

**Issue by hxtcoder** [huobiapi/huobi_Java#2]
hello,
文档上定义了`借贷账户详情的接口`,但SDK并没有提供。麻烦核实，希望后续在sdk中补充该接口

**Comment by macomfan** [comment]
正在处理，SDK中会加入借贷账户详情，预计完成时间2-3个工作日。
Thanks,
Best regards

**Comment by macomfan** [comment]
已完成
