### ISSUE TITLE
`查询借贷订单`缺少direct字段

### ISSUE THREAD

**Issue by hxtcoder** [huobiapi/huobi_Java#3]
SDK中`查询借贷订单接口`缺少direct字段，查询借贷订单默认截取更旧的数据。sdk可以完善，业务更灵活

**Comment by macomfan** [comment]
当时设计SDK时考虑到之前有些客户对direct字段比较迷惑，不知道是干什么用的，所以SDK里就去掉了。但是这个还是可以考虑加到SDK中，不作为强制参数即可，预计2-3个工作日完工。
Thanks,
Best regards

**Comment by macomfan** [comment]
已完成
