### ISSUE TITLE
OrderSource和API文档描述不一致，建议修改

### ISSUE THREAD

**Issue by shmilyLT** [huobiapi/huobi_Java#4]
com.huobi.client.model.enums.OrderSource里面和API文档描述不一致，建议修改
SPOTWEB("spot-web"), // 现货 Web 交易单
SPOTAPI("spot-api"), // 现货 Api 交易单
SPOTAPP("spot-app"), // 现货 App 交易单
MARGINAPI("margin-api"), // 借贷 Api 交易单
MARGINWEB("margin-web"), // 借贷 Web 交易单
MARGINAPP("margin-app"), // 借贷 App 交易单
FLSYS("fl-sys"), // 借贷强制平仓单（爆仓单）
INVALID("invalid");

**Comment by macomfan** [comment]
修改中，预计完工时间2-3个工作日
Thanks
Best regards

**Comment by macomfan** [comment]
已完成
