### ISSUE TITLE
关于订阅订单的疑问

### ISSUE THREAD

**Issue by BingDaXian** [huobiapi/huobi_Java#7]
![AX2TI267Y96%D18R2_DFS07](https://user-images.githubusercontent.com/49145629/56268356-b9c5ac00-6123-11e9-9864-933175fb63b3.png)
按照sdk中描述，订阅订单不是依靠订单号、而是依靠交易对来订阅，是否意味着同一交易对、只能存在一个订单？

**Comment by myarth** [comment]
同一个apiKey下，同一个交易对的下的所有订单变更都会通知
